name: Test output of OpenAI on Push

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: OpenAI
        uses: Just-Moh-it/openai@v0.0.4
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-params: ${{ toJson('{"prompt":"This is a sample prompt"}') }}
        id: openai
      - name: Print
        run: |
          echo  "${{ steps.openai.outputs.completion }}"
